drop table if exists assignment_request_mutation;
create table assignment_request_mutation (
  id int not null auto_increment,
  assignment_request_id int not null,
  type varchar(50) not null,
  client_id int,
  update_email varchar(100),
  company_name varchar(100),
  account_number varchar(50),
  adjuster_last varchar(50),
  adjuster_first varchar(50),
  adjuster_phone varchar(50),
  adjuster_email varchar(100),
  company_address1 varchar(100),
  company_address2 varchar(100),
  company_city varchar(100),
  company_state varchar(10), 
  company_zip varchar(30),
  claim_number varchar(50),
  insured_or_claimant varchar(20),
  policy_number varchar(50),
  same_as_owner tinyint(1),
  deductible_amount DECIMAL(13,2),
  claimant_first varchar(50),
  claimant_last varchar(50),
  claimant_phone varchar(50),
  claimant_email varchar(100),
  claimant_address1 varchar(100),
  claimant_address2 varchar(100),
  claimant_city varchar(100),
  claimant_state varchar(50), 
  claimant_zip varchar(30),  
  vehicle_make varchar(50),  
  vehicle_model varchar(50),
  vehicle_year varchar(10),
  vehicle_vin varchar(50),
  vehicle_license varchar(50),
  vehicle_state varchar(10),
  vehicle_location_name varchar(100),
  is_vehicle_location_repair_facility tinyint(1),
  vehicle_location_address1 varchar(100),
  vehicle_location_address2 varchar(100),
  vehicle_location_city varchar(100),
  vehicle_location_state varchar(10),
  vehicle_location_zip varchar(30),
  vehicle_location_phone varchar(50),
  loss_date datetime,
  type_of_loss varchar(50),
  loss_description text,
  has_copy_of_appraisal tinyint(1),
  has_salvage_bids tinyint(1),
  has_acv tinyint(1),
  acv_evaluation_method text,
  date_created timestamp not null default now(),
  date_modified datetime null,
  active tinyint(1) not null default 1,
  inactive_date datetime null,
  constraint pk_assignment_request_mutation_id primary key (id)
);
